server:
      port : 8082
spring:
  jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
        show-sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/pdborcl
    username: wcsadmin
    password: passw0rd
    driver-class-name: oracle.jdbc.OracleDriver 
  security:
    oauth2:
      client:
        registration:
           google:
            clientId: 825239019677-iip1m5dqnrgr7dmp67reoqi0fjqedi20.apps.googleusercontent.com
            clientSecret: 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
    thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8           

                    
  