spring:
  security:
    oauth2:
      client:
        registration:
           google:
            clientId: 825239019677-dtm8rp1r86lk1s4mk7s3qmq6euk2ahj5.apps.googleusercontent.com
            clientSecret: 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
    thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8            
server:
  port : 8082   
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver 
  jpa:
       show-sql: true
       properties: 
           hibernate: 
                dialect: org.hibernate.dialect.H2Dialect
       hibernate:
          ddl-aith: update                    
  