spring:
  security:
    oauth2:
      client:
        registration:
           google:
            clientId: 825239019677-iip1m5dqnrgr7dmp67reoqi0fjqedi20.apps.googleusercontent.com
            clientSecret: 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
    thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8   
server:
      port : 8082         
h2:
    console:
      enabled: true
      path: /h2-ui
datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver 
jpa:
       show-sql: true
       properties: 
           hibernate: 
                dialect: org.hibernate.dialect.H2Dialect
       hibernate:
          ddl-aith: update                    
  