spring:
  security:
    oauth2:
      client:
        registration:
           google:
            clientId: 82523
            clientSecret: GOCSP
    thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8            
server:
  port : 8082            
  